apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubernetes-webhooks.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubernetes-webhooks.fullname" . }}-serving-cert
  labels:
  {{- include "kubernetes-webhooks.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "kubernetes-webhooks.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate--v1-service
  failurePolicy: Fail
  name: vservice-v1.spcld.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
